import Navbar from "@/components/Navbar";
import StoreProvider from "@/store/StoreProvider";
import "./styles/globals.scss";

export const metadata = {
  title: "Task management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Navbar />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
